name: workflow

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: "unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm i

      - name: Run unit tests
        run: npm t utils

  e2e-tests:
    name: End-to-End testing
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Use PostgresSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgres db: "nc_news"
          postgres user: "testUser"
          postgres password: "testPassword"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: PGDATABASE=nc_news PGUSER=testUser PGPASSWORD=testPassword npm t app
